### ISSUE TITLE
it WON‘T change the layout.

### ISSUE THREAD

**Issue by asiyoua** [nothingislost/obsidian-workspaces-plus#89] opened 2022-11-04 01:21 UTC
**Describe the bug**
When I click on the workspace，it WON‘T change the layout.
Besides，I cannot see the same picture as you showed.
The keywords work successfully.

**Video**
attachment

**Desktop (please complete the following information):**
 - Window 10

https://user-images.githubusercontent.com/48462903/199864712-74d32eaa-9982-49dc-b8f2-15c9f3018145.mp4

**Comment by aropele** [comment] 2022-11-09 07:25
Duplicate of #87

**Comment by jsmorabito** [comment] 2022-12-11 21:03
@bxz400 is this working for you now?

**Comment by jsmorabito** [comment] 2023-05-30 01:13
should be fixed via latest update, please re open if you continue to experience this issue

**Closed by jsmorabito** 2023-05-30 01:13 UTC
